# golangci-lint configuration for HyperFleet Pull Secret Job
# https://golangci-lint.run/usage/configuration/
# Aligned with HyperFleet Linting Standard (HYPERFLEET-443)
# 15 of 16 required linters enabled (revive temporarily disabled)
version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    # HyperFleet standard linters (15 of 16 enabled)
    # TODO: Re-enable revive after adding comments to exported symbols
    - govet          # Reports suspicious constructs
    - errcheck       # Checks for unchecked errors
    - staticcheck    # Static analysis checks (includes gosimple in v2)
    - unused         # Checks for unused constants, variables, functions and types
    - ineffassign    # Detects ineffectual assignments
    - misspell       # Finds commonly misspelled English words
    - gocritic       # Provides diagnostics that check for bugs, performance and style issues
    - unconvert      # Remove unnecessary type conversions
    - unparam        # Reports unused function parameters
    - goconst        # Finds repeated strings that could be replaced by a constant
    - exhaustive     # Check exhaustiveness of enum switch statements
    # - revive       # Temporarily disabled - 44 existing violations (missing comments)
    - lll            # Reports long lines
    - gosec          # Inspects source code for security problems

linters-settings:
  gofmt:
    simplify: true

  govet:
    enable:
      - shadow

  errcheck:
    check-type-assertions: true
    check-blank: true

  revive:
    enable-all-rules: false
    rules:
      # Explicitly disable all rules with existing violations
      # TODO: Enable incrementally as comments are added
      - name: exported
        disabled: true
      - name: unexported-return
        disabled: true
      - name: var-naming
        disabled: true
      - name: package-comments
        disabled: true
      - name: redefines-builtin-id
        disabled: true
      - name: unused-parameter
        disabled: true
      - name: increment-decrement
        disabled: true

  # Settings per HyperFleet standard
  lll:
    line-length: 120

  exhaustive:
    default-signifies-exhaustive: true

  goconst:
    min-len: 3
    min-occurrences: 3

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt

output:
  print-issued-lines: true
  print-linter-name: true
