# golangci-lint configuration for HyperFleet Pull Secret Job
# https://golangci-lint.run/usage/configuration/
# Aligned with HyperFleet Linting Standard (HYPERFLEET-443)
version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    # Required linters per HyperFleet standard
    - govet          # Reports suspicious constructs
    - errcheck       # Checks for unchecked errors
    - staticcheck    # Static analysis checks (includes gosimple in v2)
    - unused         # Checks for unused constants, variables, functions and types
    - ineffassign    # Detects ineffectual assignments
    - misspell       # Finds commonly misspelled English words
    - gocritic       # Provides diagnostics that check for bugs, performance and style issues
    # Additional linters per HYPERFLEET-443
    - unconvert      # Remove unnecessary type conversions
    - unparam        # Reports unused function parameters
    - goconst        # Finds repeated strings that could be replaced by a constant
    - exhaustive     # Check exhaustiveness of enum switch statements
    # Temporarily disabled - existing code has violations, fix incrementally
    # TODO: Enable these linters after fixing existing violations
    # - revive       # Fast linter (needs comment fixes first)
    # - lll          # Reports long lines
    # - gosec        # Inspects source code for security problems

linters-settings:
  gofmt:
    simplify: true

  govet:
    enable:
      - shadow

  errcheck:
    check-type-assertions: true
    check-blank: true

  revive:
    rules:
      - name: exported
        disabled: true  # Disabled for MVP - can enable later
      - name: unexported-return
        disabled: true  # Disabled for MVP
      - name: var-naming
        disabled: true  # Disabled for MVP
      - name: package-comments
        disabled: true  # Disabled for MVP
      - name: redefines-builtin-id
        disabled: true  # Disabled for MVP
      - name: unused-parameter
        disabled: true  # Disabled for MVP
      - name: increment-decrement
        disabled: true  # Disabled for MVP

  # Settings per HyperFleet standard
  lll:
    line-length: 120

  exhaustive:
    default-signifies-exhaustive: true

  goconst:
    min-len: 3
    min-occurrences: 3

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  # Exclude some linters from running on tests files
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - lll
    # Temporarily exclude existing violations in pkg/ for incremental fixes
    # TODO: Remove these exclusions as issues are fixed
    - path: "^pkg/"
      linters:
        - revive      # Missing comments - fix incrementally
        - lll         # Long lines - fix incrementally
        - gosec       # G115 integer overflow - needs careful review
        - goimports   # Formatting issues

formatters:
  enable:
    - gofmt
    # - goimports  # TODO: Enable after fixing existing formatting issues

output:
  print-issued-lines: true
  print-linter-name: true
